# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-18 15:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160828_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
