# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180318_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
