# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markdown_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
